In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("Life Expectancy data.csv")

In [3]:
data

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [4]:
data.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [6]:
data.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [7]:
data.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [8]:
data.drop("Country",axis=1,inplace=True)

In [9]:
data["Status"] = data["Status"].map({
    "Developing":0,
    "Developed":1
})

In [ ]:
# Fill Missing Values

In [10]:
for col in data.columns:
    data[col].fillna(data[col].median(), inplace=True)

C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\PAVANKUMAR S G\AppData\Local\Temp\ipykernel_1508\2476372249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)

In [11]:
data.isnull().sum()

Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64

In [13]:
data.columns = data.columns.str.strip()

In [ ]:
# Feature Selection

In [14]:
X =data.drop("Life expectancy",axis=1)
y =data["Life expectancy"]

In [15]:
X

,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,2015,0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,2014,0,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,2013,0,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,2012,0,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,2011,0,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,2004,0,723.0,27,4.36,0.000000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,2003,0,715.0,26,4.06,0.000000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,2002,0,73.0,25,4.43,0.000000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,2001,0,686.0,25,1.72,0.000000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,2000,0,665.0,24,1.68,0.000000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [16]:
y

0       65.0
1       59.9
2       59.9
3       59.5
4       59.2
        ...
2933    44.3
2934    44.5
2935    44.8
2936    45.3
2937    46.0
Name: Life expectancy, Length: 2938, dtype: float64

In [ ]:
# Train Test Split

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [28]:
X_train

array([[-0.11655742, -0.46310937, -0.31789671, ...,  0.71301184,
        -0.15670411, -0.04397277],
       [-1.41779229, -0.46310937, -0.10996316, ...,  1.00454928,
        -0.354789  , -0.32060097],
       [ 0.75093249, -0.46310937, -0.18194016, ..., -0.11674858,
         0.49202389,  0.2633919 ],
       ...,
       [-0.11655742, -0.46310937,  0.8017455 , ..., -0.13917454,
        -0.86980971, -1.1197491 ],
       [-0.98404733,  2.15931716, -0.74975871, ..., -0.96893495,
         1.02685309,  1.03180357],
       [-0.55030238, -0.46310937, -1.0536616 , ...,  1.0494012 ,
        -3.13788167, -2.0418431 ]])

In [29]:
X_test

array([[-0.3334299 , -0.46310937, -0.34188905, ...,  0.33177057,
         0.01166804, -0.1976551 ],
       [-0.3334299 ,  2.15931716, -0.42186349, ..., -0.67739751,
         0.73963   ,  0.57075657],
       [-0.11655742, -0.46310937, -0.32589416, ..., -0.58769368,
         0.63563544,  0.47854717],
       ...,
       [ 1.6184224 , -0.46310937,  0.76975572, ...,  0.53360418,
        -0.90942668, -0.96606677],
       [-0.3334299 , -0.46310937,  0.17794484, ...,  0.39904844,
         0.58116209,  0.0789731 ],
       [ 0.10031506, -0.46310937, -0.26991205, ..., -0.54284177,
         0.57125785,  0.4478107 ]])

In [17]:
# Linear Regression

In [18]:
from sklearn.linear_model import LinearRegression

In [23]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [33]:
y_pred_lr = lr.predict(X_test)
y_pred_lr

array([67.13735915, 77.27400882, 75.71597785, 78.09083077, 46.86022592,
       50.63400816, 67.68713195, 70.78925937, 74.55048378, 54.69487415,
       51.80689301, 63.7629245 , 65.17618148, 70.43826795, 70.70412452,
       62.71128415, 55.61558454, 81.05605134, 68.72893136, 81.5916551 ,
       81.60198283, 84.22896496, 70.63801551, 68.88521236, 69.80159717,
       68.24936397, 60.76358081, 61.49630013, 78.73482393, 71.53381487,
       66.19267079, 75.32177951, 69.15435142, 68.65541615, 80.68377556,
       58.45524707, 66.98799882, 72.78003645, 62.51648154, 76.24842029,
       57.37677416, 63.98213036, 75.05979313, 81.37881329, 75.87340856,
       57.46576025, 79.28073025, 70.37313675, 66.1783163 , 67.45260062,
       57.79938488, 60.7063273 , 78.24601503, 72.54212515, 73.12902054,
       59.52165809, 75.80194722, 70.05958046, 66.73774663, 69.18197453,
       77.99423547, 54.50492665, 73.93690136, 69.69309339, 52.39477288,
       52.51538107, 53.31546175, 80.12736159, 58.74331435, 77.53765459,
       80.72769379, 75.25153477, 73.78796784, 60.46160797, 56.44173125,
       70.44481807, 63.9487502 , 77.10713982, 56.41012019, 62.51771899,
       64.09916147, 61.40318325, 67.11315025, 68.39058334, 58.74571685,
       74.74470083, 75.24564154, 68.56581155, 76.18362257, 76.02971016,
       72.96549236, 62.98219481, 72.57884051, 77.611404  , 74.19631607,
       68.34951384, 79.35464397, 71.39922173, 66.7150461 , 61.37475096,
       83.43830911, 56.09232071, 72.19117144, 53.72688959, 74.5049052 ,
       78.28119977, 70.91183124, 67.3408321 , 65.12863666, 64.55734912,
       68.74787531, 62.12248903, 49.84480479, 70.9338305 , 62.48201194,
       76.96233727, 63.93288883, 56.55769071, 65.49163865, 63.85355745,
       65.86597565, 71.7474894 , 80.79466567, 63.55007519, 58.97227125,
       65.93738247, 70.79447156, 64.61266655, 72.90269993, 71.43217128,
       75.0339643 , 81.02936212, 59.88565073, 69.52399724, 54.44447596,
       69.78319975, 75.39340861, 77.51977824, 75.6502142 , 76.61430558,
       69.36851748, 65.7327893 , 61.89720639, 59.5790438 , 58.87165918,
       64.05119833, 59.67726483, 74.89431997, 63.57420443, 75.85722219,
       79.55124287, 80.93452836, 69.72545876, 71.54245167, 80.85789058,
       77.63001112, 80.82625413, 73.68025187, 80.77757776, 78.93042062,
       73.44365116, 79.72385961, 70.19975327, 78.39158933, 67.34749764,
       63.60587539, 64.91620673, 80.68826194, 77.06369334, 74.88892212,
       81.57263353, 71.88440058, 67.19989048, 61.08180327, 71.11445926,
       64.07554102, 69.85520672, 63.53858626, 60.19349055, 71.23592991,
       83.469423  , 67.89553981, 83.35602252, 73.51040954, 79.20675165,
       35.91496361, 60.53643566, 42.71596004, 72.72014526, 73.15319529,
       64.36604499, 68.10807987, 81.45036172, 62.84119487, 75.84079827,
       67.46975644, 72.8165746 , 68.36342156, 79.7785864 , 73.38625029,
       73.28802054, 57.03741186, 73.07812932, 71.34904335, 67.7980896 ,
       49.94058351, 74.77694103, 68.03769939, 71.10958334, 82.71432499,
       60.19468596, 61.3987003 , 73.14555276, 52.43610746, 53.55114603,
       58.34866189, 60.9920451 , 73.76045948, 62.28704135, 67.20552293,
       77.68353563, 74.38483951, 69.7915685 , 79.84048286, 77.624451  ,
       50.76361325, 57.10813675, 74.39066596, 54.57382143, 62.55896722,
       69.74147316, 72.72572004, 61.11512085, 73.74974147, 72.56992647,
       53.71987491, 77.60044709, 78.46542562, 49.44009679, 71.8033131 ,
       76.48376619, 69.46768513, 72.67786015, 71.80504006, 64.25654114,
       53.33046248, 83.12165361, 76.07080786, 76.48308767, 62.30652185,
       70.10382539, 75.64685319, 58.19082476, 78.97625097, 70.20590939,
       71.76971169, 62.21871632, 79.78176649, 58.14608743, 52.12029225,
       68.80886566, 72.92657853, 60.65777102, 55.85274645, 68.11022781,
       79.6863229 , 68.92974791, 81.43505404, 58.5664149 , 61.10108709,
       55.99296987, 50.84956782, 69.74965491, 70.89379277, 54.69724744,
       72.52361499, 59.79731072, 73.63172107, 64.6851259 , 63.93505503,
       69.09924075, 80.552327  , 59.87420711, 75.90872676, 76.11467652,
       64.62660615, 78.41518215, 46.08456376, 61.26973195, 76.41970075,
       67.03111737, 69.14620651, 69.15034775, 73.0002539 , 74.45398093,
       63.09904919, 78.83845594, 71.55047463, 54.93601001, 73.52922495,
       74.03155031, 76.45993858, 69.34115033, 74.50727322, 72.78909608,
       57.24228331, 57.96148272, 50.71101889, 69.11959795, 75.28579957,
       72.6565794 , 60.93392595, 75.13990985, 64.41931896, 69.57090814,
       66.20616124, 53.96219302, 70.92000391, 55.60450873, 72.06013495,
       52.42130417, 78.07176876, 56.47195376, 70.1206129 , 69.7840921 ,
       76.62483729, 76.06462092, 70.82166706, 72.16299561, 81.93857436,
       73.45366399, 68.99135572, 68.47796031, 69.26233673, 74.88380276,
       81.41284177, 72.63374617, 76.85118328, 68.56014924, 71.54609922,
       70.19931835, 74.70828223, 72.0921956 , 74.2158832 , 70.42633471,
       50.01693857, 66.16046084, 73.28776344, 74.20965613, 74.93319657,
       62.99291711, 69.70406648, 59.22903153, 59.05113019, 72.98470197,
       79.79909355, 70.12800381, 61.38519908, 70.5718388 , 73.81997461,
       63.05381112, 73.58184136, 76.60016545, 68.29194216, 65.94411122,
       63.41037315, 60.66668207, 75.42460214, 63.45668573, 75.05742847,
       72.58089772, 55.65526338, 73.26669961, 78.35317556, 74.36038293,
       72.91041481, 58.41344404, 69.87924308, 71.10573001, 65.6573557 ,
       60.64056574, 81.70125431, 80.94158487, 80.3704388 , 63.03582388,
       55.05321689, 75.4172935 , 56.53366167, 70.72709175, 76.16860737,
       49.50388148, 79.12940302, 77.03255282, 80.43817336, 64.79348191,
       66.01611435, 79.35148918, 69.83868146, 79.47160371, 72.01506241,
       53.69104398, 76.10600437, 50.08511196, 71.90198582, 65.5635914 ,
       63.57521037, 68.95907995, 73.7004773 , 67.3599005 , 73.27684176,
       71.75763382, 81.92021267, 72.87456923, 75.57145166, 70.51586062,
       69.20892782, 60.11088847, 70.81309849, 69.14162188, 65.14753106,
       64.0319945 , 60.51081673, 70.51964344, 73.67346028, 73.45824243,
       71.25701361, 65.43686094, 64.45894016, 73.61615723, 74.64503188,
       54.5931507 , 75.72471231, 74.70037315, 67.14907224, 34.751797  ,
       65.25834463, 56.63231444, 67.95264676, 67.16728419, 73.41644201,
       75.09943972, 69.97393375, 71.10809747, 78.7226606 , 77.91152278,
       70.16995085, 76.57717969, 78.45055226, 85.2256964 , 57.35363811,
       82.25062008, 56.11958201, 69.87465828, 73.057035  , 52.52351235,
       76.3530254 , 83.92637565, 51.98981408, 66.88727992, 76.70326613,
       73.65029601, 70.48217961, 61.64734395, 66.79092916, 64.40151415,
       57.4475181 , 79.065471  , 71.32536382, 80.11248631, 69.72023487,
       68.26563583, 76.64834939, 73.82378147, 71.36362553, 82.65675048,
       71.18586538, 67.34612796, 69.40263718, 80.94592347, 71.32916459,
       75.32590514, 71.10183358, 70.60493997, 75.97736821, 69.3670138 ,
       82.14658798, 77.90668315, 80.21683528, 71.81031343, 73.96391468,
       73.80031506, 74.4197044 , 49.42959515, 70.44489281, 74.62745439,
       62.75283414, 80.27141227, 72.07901447, 61.78036648, 72.6234503 ,
       74.48503304, 58.2364554 , 80.17540355, 70.85676476, 76.73162155,
       78.46914417, 68.47501246, 81.90365298, 75.32814599, 69.83269561,
       65.12420745, 67.6612695 , 69.2605882 , 73.20298553, 48.0722942 ,
       65.42207775, 63.03912136, 64.44195809, 65.76017979, 59.47510556,
       73.73666622, 78.05005013, 71.9500377 , 73.22222854, 68.00544965,
       63.61772441, 66.3786668 , 70.89142409, 75.85340663, 81.5465243 ,
       57.07744257, 72.50279907, 69.458629  , 79.30807838, 66.21415314,
       79.24264845, 69.81879293, 78.73459724, 82.1312682 , 82.46174819,
       80.35844832, 48.41135308, 64.7053445 , 68.03967924, 75.52918552,
       64.25031016, 70.71570912, 61.40001384, 63.79793687, 69.88523618,
       77.78469385, 56.52732006, 79.42417399, 60.20878231, 74.54652676,
       67.44069053, 77.9619826 , 68.25434061, 70.76691427, 78.18037816,
       66.01725219, 82.89981283, 84.65654484, 75.63909047, 51.57235669,
       75.74633052, 77.72204417, 84.20798685, 59.0891477 , 72.33848375,
       73.65574196, 63.22423875, 78.36604657, 68.88316886, 74.22142492,
       65.83221233, 68.85567132, 71.46417416, 61.52644213, 75.98343677,
       53.93646231, 78.14493829, 81.37813538, 58.76020999, 76.44732811,
       63.74583353, 70.28531617, 73.73060563])

In [34]:
# Ridge

In [35]:
from sklearn.linear_model import Ridge

In [36]:
ridge = Ridge()
ridge.fit(X_train, y_train)

Ridge()

In [39]:
y_pred_ridge = ridge.predict(X_test)
y_pred_ridge

array([67.10367304, 77.2621633 , 75.75359699, 78.12487452, 46.90483941,
       50.69919068, 67.65852545, 70.78232561, 74.55888018, 54.65275522,
       51.86065418, 63.76059248, 65.19305093, 70.48241569, 70.69546091,
       62.64720269, 55.5544389 , 81.0421048 , 68.71631907, 81.61703553,
       81.60929232, 84.24147748, 70.63889993, 68.87809588, 69.80376507,
       68.22155263, 60.7310648 , 61.47740384, 78.75984304, 71.54561802,
       66.16648234, 75.32219051, 69.11499919, 68.66137872, 80.65986838,
       58.49243976, 67.03511635, 72.80365244, 62.45870788, 76.2866318 ,
       57.36165485, 63.99503999, 75.08047904, 81.38092787, 75.89460147,
       57.4251535 , 79.27040912, 70.41810571, 66.25433857, 67.46066123,
       57.83047745, 60.53301503, 78.26590697, 72.52028161, 73.15260956,
       59.54735246, 75.76832522, 70.10267148, 66.71240172, 69.19239655,
       77.95189132, 54.44621672, 73.94609807, 69.70753149, 52.3549869 ,
       52.54090106, 53.3013622 , 80.12100906, 58.736247  , 77.50595185,
       80.71857655, 75.27007998, 73.82157267, 60.5043029 , 56.32641848,
       70.44145598, 63.93034436, 77.1603583 , 56.32257991, 62.44615077,
       64.10125109, 61.46710525, 67.1148258 , 68.40114279, 58.61678755,
       74.65235684, 75.28124797, 68.51660676, 76.18071479, 76.03562547,
       72.96933229, 63.06787527, 72.58921981, 77.63352041, 74.19967121,
       68.30869897, 79.38282104, 71.34814675, 66.6981802 , 61.37918943,
       83.45184195, 56.14683811, 71.53204662, 53.71018531, 74.53259397,
       78.30083402, 70.91217804, 67.30296132, 65.0722186 , 64.57589345,
       68.73890226, 62.05622398, 49.80872283, 70.2858135 , 62.5632686 ,
       76.99555612, 64.02073737, 56.49196477, 65.45826062, 63.83120907,
       65.49115714, 71.73981541, 80.82895526, 63.5761034 , 59.0212642 ,
       65.9067915 , 70.78271185, 64.59590834, 72.90916201, 71.45820558,
       74.94120097, 81.0467902 , 59.83753366, 69.54920885, 54.69409461,
       69.77955144, 75.44186757, 77.52346661, 75.66679355, 76.62045411,
       69.33688156, 65.74120154, 61.88206849, 59.51496448, 58.88200402,
       63.99701821, 59.62901474, 74.89776187, 63.62757655, 75.85901021,
       79.57434572, 80.96169824, 69.71231001, 71.6059118 , 80.86422848,
       77.60845368, 80.82273142, 73.66414944, 80.75737405, 78.94699307,
       73.4625593 , 79.75603202, 70.1794905 , 78.4085207 , 67.2991843 ,
       63.61778589, 64.85473687, 80.72246217, 77.10470085, 74.91040294,
       81.60348882, 71.91064383, 67.11673234, 61.07841553, 71.09997706,
       64.06269405, 69.82416669, 63.52028928, 60.12678766, 71.23819492,
       83.46544536, 67.89814438, 83.35673037, 73.54697686, 79.22051696,
       35.87450124, 60.51577133, 43.12017771, 72.72751718, 73.1330376 ,
       64.36698418, 68.11161536, 81.44095316, 62.81540612, 75.81761619,
       67.51833086, 72.841988  , 68.30540139, 79.78329623, 73.40055852,
       73.27861776, 57.05573984, 73.09834728, 71.28548931, 67.36768187,
       51.0585187 , 74.77549306, 68.03714468, 71.10949674, 82.73791502,
       60.18583951, 61.38163625, 73.14550805, 52.41910242, 53.54876545,
       58.32928712, 60.92623913, 73.77526292, 62.26175545, 67.22220692,
       77.66161749, 74.38428933, 69.73409872, 79.85159404, 77.62178933,
       50.85085229, 57.24228442, 74.38467556, 54.6907843 , 62.47727405,
       69.7214001 , 72.73090491, 61.00588032, 73.74783843, 72.59103984,
       53.67293534, 77.62171596, 78.43891738, 49.41644487, 71.79182941,
       76.47696691, 69.45447945, 72.69539639, 71.81481593, 64.19414751,
       53.44111437, 83.1312169 , 76.06263704, 76.47597215, 62.26377997,
       70.12265714, 75.68589347, 58.26743718, 78.97412619, 70.20914872,
       71.79546851, 62.22217595, 79.76659648, 58.09195853, 52.08762755,
       68.81744709, 72.92818703, 60.61186496, 55.952299  , 68.07228216,
       79.67269726, 68.7253424 , 81.42844281, 58.55400646, 61.18194799,
       56.15437806, 50.93925932, 69.66980303, 70.94247048, 54.62366328,
       72.52943459, 59.84408973, 73.66556186, 64.64042798, 63.87903913,
       69.10590845, 80.56400037, 59.86471659, 75.9521989 , 76.13402838,
       64.61582138, 78.42017709, 46.09612967, 61.20299808, 76.45620118,
       67.00774014, 69.18732304, 68.86576863, 72.96847232, 74.493661  ,
       63.02141916, 78.82556719, 71.55133849, 55.00138699, 72.85204929,
       73.98285648, 76.47735131, 69.28981657, 74.52117963, 72.77418578,
       57.35984612, 57.99054912, 51.52494638, 69.11411284, 75.29103868,
       72.63082846, 60.85618234, 75.20097487, 64.39069562, 69.53362461,
       66.18961974, 54.01291306, 70.95641313, 55.82755011, 72.04884001,
       52.37984677, 78.07802856, 56.50167365, 70.13809747, 69.78195779,
       76.66725882, 76.09700133, 70.84583916, 72.20057309, 81.9570702 ,
       73.46535782, 68.98539818, 68.4537436 , 69.26930214, 74.88590067,
       81.3919933 , 72.61321982, 76.83536898, 68.50568841, 71.56907085,
       70.16443238, 74.71088537, 71.44623467, 74.2654066 , 70.38538723,
       49.9803117 , 66.21470466, 73.31734366, 74.0240041 , 74.95816928,
       63.02484003, 69.49358628, 59.22253198, 59.01708289, 72.97569703,
       79.83741953, 70.12526673, 61.32955812, 70.54493864, 73.81452489,
       63.02960829, 73.59974072, 76.61006527, 68.30122246, 65.8772764 ,
       63.44006486, 60.65875473, 75.4723962 , 63.5008071 , 75.09826786,
       72.57630513, 55.60147202, 73.27066943, 78.35940224, 74.34759946,
       72.82815907, 58.40799392, 69.91691671, 71.10535197, 65.71035876,
       60.65003794, 81.69874772, 80.95166899, 80.40567845, 63.00200053,
       55.06448834, 75.44584342, 56.52796713, 70.70550527, 76.16522645,
       50.27400768, 79.11250825, 77.02573596, 80.42266723, 64.76042242,
       66.07386551, 79.34767269, 69.80522332, 79.48377828, 72.04261112,
       53.77699166, 76.13030473, 50.05007678, 71.92861804, 65.57338309,
       63.51219123, 68.97556247, 73.70462632, 67.37735323, 73.31069538,
       71.80339441, 81.86691288, 72.85364639, 75.57357959, 70.50103565,
       69.1094505 , 59.59561024, 70.77792184, 69.12188883, 65.08767021,
       64.00494823, 60.46144211, 70.51752555, 73.68555811, 73.4342404 ,
       71.29904536, 65.4472603 , 64.47668407, 73.63288627, 74.67610339,
       54.56236687, 75.75788277, 74.07396071, 66.99323095, 34.74306541,
       65.2629092 , 56.70726644, 67.94816897, 67.17465033, 73.42691622,
       75.12618838, 69.96694378, 71.11815039, 78.69616026, 77.93427208,
       70.19253812, 76.58474297, 78.43924444, 85.25243123, 57.24040417,
       82.25543816, 56.35261171, 69.87549347, 73.05429688, 52.57666256,
       76.33305894, 83.92972718, 52.07247703, 66.93475339, 76.69890053,
       73.68175814, 70.5024796 , 61.63669382, 66.77706154, 64.34879663,
       57.58872633, 79.07426503, 71.31977694, 80.08312504, 69.69565351,
       68.26741012, 76.68530284, 73.70039882, 71.37416914, 82.66741168,
       71.18477701, 67.35532099, 69.39927115, 80.9454849 , 71.25708886,
       75.372803  , 71.09437779, 70.64853777, 75.94081128, 69.36356792,
       82.12097946, 77.90646964, 80.20898147, 71.75190705, 74.01221645,
       73.79583006, 74.25242994, 49.56234233, 70.44200484, 74.63444853,
       62.43983775, 80.28360501, 72.08488664, 61.77002083, 72.62673487,
       74.02536667, 58.37202362, 80.21269357, 70.86878483, 76.72949308,
       78.48662628, 68.40181469, 81.90353636, 74.94884909, 69.78235918,
       65.16626256, 67.58205134, 69.23942272, 73.23947947, 48.18141085,
       65.42726123, 63.00735249, 64.44251347, 65.70778483, 59.49265313,
       73.71157141, 78.06263901, 71.99333658, 73.23491586, 67.96077463,
       63.60388027, 66.4332122 , 70.90187848, 75.80467495, 81.53886417,
       57.13596419, 72.53434465, 69.43235247, 79.33641773, 66.20746259,
       79.25425612, 69.74996952, 78.73228524, 82.14455821, 82.46702071,
       80.36778383, 48.43224103, 64.73884372, 68.01400546, 75.56314994,
       64.25906711, 70.53763148, 61.40120781, 63.73400115, 69.85151256,
       77.78465486, 56.52793638, 79.44135376, 60.20126614, 74.53817128,
       67.41461605, 77.96077095, 68.03159321, 70.81499974, 78.18609058,
       65.98591371, 82.91324144, 84.66336861, 75.67221921, 51.51542133,
       75.78342173, 77.72849678, 84.21988782, 59.07408214, 72.36582753,
       73.65214635, 63.20556176, 78.3640112 , 68.86789023, 74.19631551,
       65.79131831, 68.83342196, 71.46520374, 61.60267066, 75.9829513 ,
       53.8641508 , 78.10016884, 81.38129487, 58.74353645, 76.49307458,
       63.7362844 , 70.29614151, 73.72280076])

In [40]:
# Lasso

In [41]:
from sklearn.linear_model import Lasso

In [42]:
lasso = Lasso()
lasso.fit(X_train, y_train)

Lasso()

In [43]:
y_pred_lasso = lasso.predict(X_test)
y_pred_lasso

array([68.52577953, 75.16127167, 73.58528378, 77.3893608 , 52.46548217,
       53.65795394, 68.16899274, 70.87862564, 74.28481525, 56.58299658,
       55.36800102, 64.50847126, 66.15003243, 70.93252511, 70.46177938,
       63.16677233, 58.01398291, 78.12922722, 68.81220681, 78.96834543,
       78.45982149, 81.13279804, 70.12582144, 68.44311782, 69.92640998,
       68.5929346 , 60.97806241, 61.90375247, 78.01018242, 70.96377118,
       66.33451706, 74.67495517, 67.32812279, 68.38999651, 76.08898834,
       59.77283896, 67.94955054, 72.65202824, 62.0675787 , 75.96309828,
       59.53855158, 64.82224076, 73.779935  , 79.71248328, 75.49460137,
       60.11281667, 77.18261785, 71.07333139, 66.95376459, 67.96003641,
       62.38481471, 62.31312156, 77.50712838, 72.06264781, 73.22522512,
       60.93740774, 74.17931243, 70.52765101, 68.4780581 , 69.81248966,
       75.57800069, 57.7535342 , 73.83177739, 69.94094402, 55.1923877 ,
       55.92997263, 54.5592319 , 78.01924017, 59.14655827, 77.41076631,
       77.28610424, 74.82934302, 73.60875045, 61.91699103, 57.53336321,
       69.91925045, 64.38494896, 77.32402494, 58.85526683, 62.37687377,
       64.7904785 , 62.31306612, 66.85115948, 68.07328692, 61.16078374,
       75.59549154, 75.05193378, 67.85505163, 74.53080997, 74.93740781,
       72.49692097, 65.35354849, 72.23725641, 77.17746954, 73.44633168,
       68.23520809, 78.27621832, 70.78420867, 66.65004068, 62.41337504,
       79.44104079, 57.86147455, 71.48941809, 56.08336233, 74.80550192,
       75.28138454, 70.42154297, 65.80843086, 66.24512528, 65.41681827,
       68.98591825, 62.30242556, 53.59997316, 69.83234586, 64.11934499,
       76.31062405, 65.93150595, 58.73290857, 66.1561275 , 64.24073067,
       63.38365372, 71.21681616, 78.55721534, 64.73668484, 60.47328579,
       66.32396051, 70.97331662, 65.24003338, 72.48166065, 71.62267649,
       73.47027788, 77.75924236, 58.47817982, 68.31100306, 60.57993719,
       69.25939577, 75.5913957 , 75.6700287 , 74.17180025, 76.26819573,
       69.30538489, 66.51899199, 62.86880616, 60.2785955 , 60.67294114,
       63.50491331, 58.26287565, 74.43748979, 64.76456026, 75.13601302,
       78.16441176, 77.24471257, 69.47659424, 72.44689001, 78.02750236,
       75.62461468, 77.68516447, 73.29997769, 78.52292502, 77.14958603,
       72.07659293, 76.57564913, 69.92308083, 77.37151076, 68.71899456,
       63.95214064, 65.8921372 , 79.53617139, 76.49010947, 74.2782608 ,
       79.9350706 , 72.01464439, 65.83279697, 62.01805222, 71.22608026,
       63.53903239, 70.36742006, 63.91233867, 61.39992427, 71.12426488,
       80.10602121, 68.23500853, 79.78897856, 73.30754024, 77.9031339 ,
       40.84747166, 60.92575489, 49.90385444, 72.51390706, 71.90537684,
       65.0958901 , 67.65631263, 79.54640834, 63.36010762, 73.92780707,
       68.51563829, 72.79371478, 67.92001607, 78.03216894, 72.8726456 ,
       71.86859406, 58.35986012, 72.67602276, 70.63286086, 65.12224286,
       63.86756712, 74.1060407 , 67.52932096, 70.95337462, 79.88683342,
       60.29419691, 62.63153488, 72.51276348, 52.03865047, 57.83429653,
       60.65398562, 64.44973237, 73.47666288, 62.68890389, 68.26218452,
       75.72841626, 73.77541987, 70.56896647, 78.27733795, 76.85284062,
       54.85185285, 61.31732768, 73.78103919, 55.56307736, 62.6269917 ,
       69.97315313, 72.38020146, 60.88482379, 73.37605281, 72.28549092,
       56.4607683 , 77.0762402 , 76.43948265, 52.52104104, 71.05369711,
       75.29126258, 68.93595151, 72.53526553, 72.24625883, 65.52812762,
       54.76530225, 78.49174884, 74.6576918 , 74.81086291, 63.83172977,
       70.49110493, 75.81911665, 60.69569263, 76.68259927, 70.23703619,
       71.79344742, 62.57773315, 76.86168237, 59.91755583, 51.75109721,
       69.38015763, 70.31243514, 60.51841795, 58.52354345, 67.08472043,
       76.91012606, 68.45299956, 77.95853616, 59.35579905, 64.28462396,
       57.49669884, 54.30086445, 70.01802346, 71.82900003, 57.77227193,
       72.24381259, 61.01257595, 73.54822807, 64.43976894, 63.265922  ,
       69.7230003 , 79.22501047, 60.96936769, 75.93002759, 75.92363181,
       64.98942946, 77.02325486, 50.35224851, 62.11916856, 76.29686311,
       67.25312629, 69.92815907, 66.66845928, 71.56639744, 74.53634258,
       62.93390336, 76.71623758, 71.33885856, 59.06034479, 70.77241902,
       73.23393934, 76.2191068 , 69.93120049, 74.44937571, 72.28230924,
       59.22525725, 62.48157011, 59.46474612, 68.94802711, 74.75580863,
       73.53861785, 63.94616205, 75.28698219, 64.37255939, 71.39186452,
       66.36760528, 57.85223385, 70.80554141, 58.34853191, 71.71607495,
       51.99393017, 76.72714612, 57.83255405, 70.2487918 , 69.61922698,
       76.1608769 , 75.3100143 , 70.99109936, 72.18887155, 80.60381695,
       72.65156043, 69.48171684, 69.61301976, 69.11162441, 74.52492138,
       78.38109253, 71.85325115, 75.01977277, 68.26714073, 70.44615495,
       70.06298591, 74.0530548 , 70.86706244, 74.80325046, 70.93539352,
       53.96153252, 67.37792445, 73.24356458, 72.23019906, 74.51538481,
       63.75742055, 69.15447134, 59.5944265 , 60.27268559, 72.55448862,
       78.5334362 , 69.60189006, 60.6462126 , 71.01785867, 73.32435446,
       64.44980889, 73.04973011, 74.31568725, 68.17894057, 66.40118371,
       64.55612071, 61.58228044, 75.65670137, 64.35695079, 74.77893307,
       72.01563143, 56.4444205 , 73.2548306 , 75.77991409, 73.7567211 ,
       72.1755525 , 59.347143  , 70.8535194 , 71.33484045, 67.00107602,
       62.23221896, 78.82229129, 79.05953984, 79.04735268, 62.81307061,
       57.86530926, 73.66347668, 58.75967568, 69.95173208, 74.61179168,
       59.2342785 , 76.59151955, 75.61546697, 76.91709638, 65.10559848,
       68.14586094, 76.83854614, 70.75507014, 78.06776967, 72.10869247,
       56.20927204, 74.45998212, 53.70450957, 71.24530719, 65.7871834 ,
       65.54927658, 68.72380426, 72.90739977, 68.18864209, 73.40659138,
       72.36795675, 75.53411533, 72.29921599, 74.83642162, 69.82172638,
       68.91563597, 62.5943349 , 71.00367338, 69.25044859, 66.05213246,
       64.49957358, 61.8477829 , 70.50243903, 73.19061464, 73.1012344 ,
       71.58714981, 65.81927806, 65.16385714, 73.34274119, 74.77841602,
       58.19203479, 74.47078506, 70.46096854, 67.94256169, 41.02040719,
       66.07904996, 58.99139269, 67.60418015, 68.41249575, 73.55438037,
       74.58876852, 69.89389514, 70.58420141, 76.01062516, 77.33608198,
       70.51988387, 75.62906581, 75.61916674, 81.08477662, 58.89041737,
       78.80509184, 59.61376267, 69.75907601, 72.33924804, 55.65707751,
       74.38830265, 80.21049113, 55.2150597 , 67.96434466, 75.38990944,
       74.02869259, 71.31271623, 62.67219529, 67.31304316, 67.07006464,
       58.94231091, 76.38046532, 70.86106997, 76.74687547, 69.52264392,
       68.80153417, 76.21490952, 71.92850176, 71.56912917, 78.86837941,
       71.00891733, 67.36166945, 69.2091966 , 78.51455058, 71.41636414,
       75.36270434, 70.67046743, 71.06632431, 74.60160253, 69.15044291,
       76.39716666, 77.09353782, 77.32862817, 71.12238899, 74.06388275,
       72.33583286, 72.60262734, 52.70571681, 70.45909634, 73.32416016,
       62.04362159, 79.13441964, 71.97428906, 61.82418664, 72.14989496,
       72.246689  , 59.64992491, 78.66335081, 70.51718153, 75.28164784,
       77.44599179, 67.35147855, 79.52356344, 72.58028355, 69.02132984,
       65.85220475, 66.86591698, 69.18352468, 73.25880931, 51.73124032,
       65.90341212, 63.11517965, 63.94791103, 66.30649941, 60.70094407,
       72.81261594, 77.09686382, 72.17888383, 72.97468033, 66.22584149,
       64.10209364, 67.21860392, 70.51293394, 73.48257545, 77.77352584,
       59.52810636, 71.06329702, 70.24815622, 76.22868511, 67.43358198,
       76.53972606, 68.87058099, 77.72731041, 78.36597826, 79.95845614,
       76.78739301, 52.92679551, 66.50450131, 67.84989528, 75.35190531,
       65.08900194, 69.98534794, 62.16552325, 65.77555172, 68.95932875,
       77.03438071, 58.60685588, 77.84143029, 60.60605077, 74.27684553,
       68.00081523, 76.44533912, 67.49971755, 71.34103631, 76.79873586,
       64.67883598, 80.38677576, 79.01513079, 75.46713561, 53.19382952,
       75.49756071, 76.40302069, 80.89122482, 59.81944106, 72.13954685,
       73.26952547, 63.55699487, 76.70463594, 68.81521609, 72.79731012,
       64.95734997, 68.86488349, 71.01588974, 64.4701182 , 74.46117011,
       55.24993488, 75.56998146, 79.16744564, 59.07330075, 75.57719878,
       63.87379842, 70.38978325, 73.34038841])

In [ ]:
# Comparision

In [44]:
from sklearn.metrics import r2_score, mean_squared_error

In [45]:
results = pd.DataFrame({
    "Model": ["Linear Regression","Ridge","Lasso"],
    "R2 Score": [
        r2_score(y_test, y_pred_lr),
        r2_score(y_test, y_pred_ridge),
        r2_score(y_test, y_pred_lasso)
    ]
})

results

               Model  R2 Score
0  Linear Regression  0.823552
1              Ridge  0.823155
2              Lasso  0.775510